name: SAST

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: semgrep/semgrep-action@713efdd345f3035192eaa63f56867b88e63e4e5d
        with:
          config: p/default
